# -*- coding: utf-8 -*-
"""AutoContactBook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeezFNGzm8AmUVy5EUOfb6S6Qxr5Hbtp
"""

import sqlite3
from rich.console import Console
from rich.table import Table

# Set up SQLite database
conn = sqlite3.connect("contacts.db")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT
)
""")
conn.commit()

# Helper functions
def add_contact(name, email, phone):
    cursor.execute("INSERT INTO contacts (name, email, phone) VALUES (?, ?, ?)", (name, email, phone))
    conn.commit()

def search_contact(query):
    cursor.execute("SELECT * FROM contacts WHERE name LIKE ? OR phone LIKE ?", (f"%{query}%", f"%{query}%"))
    return cursor.fetchall()

def display_contacts():
    cursor.execute("SELECT * FROM contacts")
    contacts = cursor.fetchall()
    table = Table(title="Contact List")
    table.add_column("ID", justify="right")
    table.add_column("Name", justify="left")
    table.add_column("Email", justify="left")
    table.add_column("Phone", justify="left")
    for contact in contacts:
        table.add_row(str(contact[0]), contact[1], contact[2], contact[3])
    console = Console()
    console.print(table)

# Text-based User Interface (TUI)
console = Console()
console.print("[bold green]Welcome to the Contact Book Application![/bold green]")

while True:
    console.print("\n[cyan]Options:[/cyan]\n1. Add Contact\n2. Search Contact\n3. Display All Contacts\n4. Exit")
    choice = console.input("Enter your choice: ")

    if choice == "1":
        name = console.input("Name: ")
        email = console.input("Email: ")
        phone = console.input("Phone: ")
        add_contact(name, email, phone)
        console.print("[bold green]Contact successfully added![/bold green]")

    elif choice == "2":
        query = console.input("Search: ")
        results = search_contact(query)
        if results:
            for result in results:
                console.print(f"[yellow]ID: {result[0]}[/yellow] | Name: {result[1]} | Email: {result[2]} | Phone: {result[3]}")
        else:
            console.print("[red]No contact found![/red]")

    elif choice == "3":
        display_contacts()

    elif choice == "4":
        console.print("[bold green]Goodbye![/bold green]")
        break

    else:
        console.print("[red]Invalid option, please try again![/red]")